### PR TITLE
Feature/OracleDB-conversion

### PR DESCRIPTION
**Pull request by christianelliott**
## Problem

Converts from cx_Oracle to the replacement OracleDB

## Proposed changes

Converts from cx_Oracle to OracleDB package:
https://python-oracledb.readthedocs.io/en/latest/index.html

OracleDB includes a thin client by default, and as a result the instantclient would no longer be a required dependency for this tap. This will also improve compatibility for development environments on arm64, like M1/M2 Macs where there is not a native instantclient.

This is mostly a drop in place, as there is backwards compatibility with cx_Oracle. I've converted the arguments in oracledb.connect() functions to be keyword arguments per the documentation and while I have changed the OutputTypeHandler to use the new OracleDB package, these types will be deprecated in the future.

As far as other items documented in the [Upgrading from cx_Oracle to OracleDB section](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#upgrading-from-cx-oracle-8-3-to-python-oracledb), I don't believe any of these are applicable to this tap.

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [X] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [X] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions](https://github.com/s7clarke10/pipelinewise-tap-oracle)

### CODE REVIEW

**Comment by shriv** [comment]
Hi @christianelliott .. Do you know when this will be merged in? I want to run `tap-oracle` from a M1 mac and would love to be able to use this tap natively rather than within Docker since `cx_oracle` needs the Instant Client Driver.. :-)

**Comment by s7clarke10** [comment]
Hi, sorry for not responding to this PR for some time. The key reason for my delay is backward compatibility with older Oracle versions. We have to support versions back to 11.2. I understand the libraries `thin` mode will not support older versions of Oracle. I am yet to explore whether the `thick` version of this library works with older versions.

**Comment by s7clarke10** [comment]
I am also keen to run a cprofile over the two version to get some timings between the different libraries. I note that looking at SQLAlchemy, it seems that `OracleDB` is the way forward over `cx_Oracle`.

**Comment by s7clarke10** [comment]
@christianelliott , how do you feel about a conditional statement around the imports?

The setup.py would include both drivers. The import statements for each python program would allow config to set what driver to use. It would mean that I could still use cx_Oracle on my ancient Oracle 11.2 database. For backwards compatibility I would be inclined to have the cx_Oracle as the default with good instructions in the README.md on how to swap the driver.

e.g. 

```python
if <logic to test a config item on oracle driver = "oracledb">:
    import oracledb
else:
    import cx_Oracle as oracledb
```

**Comment by temminks** [comment]
What can we do now, if @christianelliott is no longer responding? I think it would be important to offer the possiblity to use the updated `oracledb` package and your suggestion to use the config file seems like a reasonable choice to retain backwards compatibility with Oracle 11.2 - especially if the API for both packages is the same.

**Comment by s7clarke10** [comment]
Great, thanks for the feedback @temminks , I will look to implement this. It has been a bit of a backlog item for me - busy with other activities. I will look to implement this over the next few weeks - unfortunately I have higher priority items that I need to finish first but this is a good reminder - thank you. I also have as a work in progress, a piece of work looking at speeding up the json processing looking at msgspec rather than ujson.

**Comment by s7clarke10** [comment]
Hi @temminks , @christianelliott , @mjsqu

I have built an alternative PR which should support a configurable option of `oracleDB` or `cx_Oracle` libraries. It should also work with a MacOS as well.

I would be very much interested in your review, and if possible testing if you use a MacOS.

Keen to push this through as it will provide better connection options for tap-oracle.

Thanks
Steve

**Comment by s7clarke10** [comment]
@shriv , are you able to test this PR on a M1 Macbook, it would be good to verify if this new feature works? Thanks

**Comment by s7clarke10** [comment]
Thank you for raising this PR. This has been closed in favour of a configurable driver.

Here is a link to the PR which was implemented.

https://github.com/s7clarke10/pipelinewise-tap-oracle/pull/17

**Pull request closed without merging**
